name: Trivy Scan

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy scan (table)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            aquasec/trivy:0.69.3 fs /project \
            --format table \
            --severity CRITICAL \
            --ignore-unfixed

      - name: Run Trivy scan (SARIF)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            aquasec/trivy:0.69.3 fs /project \
            --format sarif \
            --output /project/trivy-results.sarif \
            --severity CRITICAL \
            --ignore-unfixed

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif
